### ISSUE TITLE
Type 'String' has no member 'forwards'

### ISSUE THREAD

**Issue by ahmadansari** [krimpedance/KRActivityIndicatorView#3]
`KRActivityIndicatorView.swift:203:31: Type 'String' has no member 'forwards'`

`.forwards` should be replaced with kCAFillModeForwards to work with latest Swift version 4.2 and Xcode 10.1

**Comment by krimpedance** [comment]
@ahmadansari 
What version of KRActivityIndicatorView are you using?

**Comment by krimpedance** [comment]
no response
